export const ActionType = {
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    LOGOUT: 'LOGOUT',
    GET_USER_LOGIN_BY_ID: 'GET_USER_LOGIN_BY_ID',
    GET_USER_LOGIN_BY_USERNAME: 'GET_USER_LOGIN_BY_USERNAME',
    FIND_USER_BY_USER_ID: 'FIND_USER_BY_USER_ID',
    FIND_USER_BY_USERNAME: 'FIND_USER_BY_USERNAME',
    CONNECT_TO_USER: 'CONNECT_TO_USER'
}